# Generated by Django 5.1.1 on 2024-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='quality',
            field=models.CharField(default='HD', max_length=150, verbose_name='Quality'),
        ),
    ]
